sudo: false
language: c
os:
  - osx
  - linux
compiler:
  - clang
  - gcc
addons:
  apt:
    packages:
      - gfortran
matrix:
  allow_failures:
    - env: MPI_IMPL=openmpi
env:
  - MPI_IMPL=mpich
  - MPI_IMPL=openmpi
before_install:
  - export TRAVIS_ROOT=$HOME/travis
  - mkdir $TRAVIS_ROOT
  - sh ./travis/install-autotools.sh $TRAVIS_ROOT
install:
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew update; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew install gcc; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew install coreutils; fi
  - sh ./travis/install-mpi.sh $TRAVIS_ROOT $MPI_IMPL
script:
  - sh ./travis/build-run.sh $TRAVIS_ROOT $MPI_IMPL
after_failure:
  - cat ./config.log
  - cat ./test-suite.log
  - find . -name "*.log" -exec head -n 100 {} ";"
